### ISSUE TITLE
Error message: Could not find diff info

### ISSUE THREAD

**Issue by lfolco** [elgentos/magento2-upgrade-gui#1]
I'm seeing this type of error message for all the options in the dropdown:

![image](https://user-images.githubusercontent.com/1709329/147287054-a01a7cbd-c68c-494e-98ab-c7d03239150d.png)

And for the one diff that does work, it seems to be pulling the wrong file:

![image](https://user-images.githubusercontent.com/1709329/147287132-f93eff60-5c8e-455e-8d2e-623f18fd2477.png)

I confirmed that I'm using the latest version of the upgrade patch helper and that I have all the required files in my Magento project directory.

**Comment by peterjaap** [comment]
Looks like the `vendor_files_to_check.patch` file isn't parsed correctly. Could you maybe share that file here (or with me privately if it contains sensitive information)?

**Comment by peterjaap** [comment]
You might be able to debug yourself too, this is where the logic happens; https://github.com/elgentos/magento2-upgrade-gui/blob/084bfbc3ef27352253f3dcfdaff021810972d27a/src/background.js#L75

We had an issue with the `--color` argument for the `diff` command internally. Maybe your machine doesn't add `--color` by default? Removing `--color` from that line would then fix it. If so, we should fine a better solution for parsing the vendor file. It's kinda hack & slash at the moment ;)

**Comment by peterjaap** [comment]
This was the commit that added `--color`; https://github.com/elgentos/magento2-upgrade-gui/commit/006aec58dbe46eb8d80f06d8ca4dfe1c90fecf0c

**Comment by lfolco** [comment]
It was the color thing; removing it makes it work.

**Comment by peterjaap** [comment]
Ok I just removed it, it works without it too :) https://github.com/elgentos/magento2-upgrade-gui/commit/a63857c9e0994e3d5f37a533a2c2320607a151b3

**Comment by lfolco** [comment]
thank you!
