### ISSUE TITLE
Clarification / Question: Resync from new patch-helper-output.txt

### ISSUE THREAD

**Issue by amenk** [elgentos/magento2-upgrade-gui#10]
Am I assuming correctly, that once the GUI was started and the results.md / warnings.json is created, the patch-helper-output.txt is no longer used?

I am asking because the Hyvä integration is still under development and I generated plenty of new patch-helper-output.txt files.
I already tracked some changes in the warnings.json (resolved issues) and would like to avoid to tag everything manual again.

I absolutely take "no, that is not possible" as an answer. We just might add an additional sentence to

https://github.com/elgentos/magento2-upgrade-gui#output

"Remark: Once the GUI was started and those files were generated, patch-helper-output.txt is no longer taken into account."

**Comment by peterjaap** [comment]
Your assumption is correct, the patch-helper-output.txt file is only used here on line 277; https://github.com/elgentos/magento2-upgrade-gui/blob/281bcba7d94c607900b47a4d8bf7934a3ea07b32/src/background.js#L269-L288

Right now it still does a check every time the application starts, so we can remove that check when the result files are present.
