### ISSUE TITLE
Opening the files via link breaks with PhpStorm 2022.3

### ISSUE THREAD

**Issue by DanieliMi** [elgentos/magento2-upgrade-gui#11]
With PhpStorm 2022.2.4 this request still works:
```
GET http://localhost:63342/api/file?file=vendor/magento/framework/App/ObjectManager.php
```
In 2022.3 it does not work anymore.

I presume this is a bug in PhpStorm since nothing is mentioned in the [release notes](https://youtrack.jetbrains.com/articles/WI-A-231736029/PhpStorm-2022.3-223.7571.212-build-Release-Notes).

**Comment by DanieliMi** [comment]
Perhaps we can add an option to choose between the PhpStorm file api or to use the "Remote call" plugin.

**Comment by peterjaap** [comment]
I thought the Remote Call plugin wasn't supported any more? That's why I switched to the file API recently.

**Comment by peterjaap** [comment]
https://plugins.jetbrains.com/plugin/6027-remote-call

> Updated 3 years ago

**Comment by DanieliMi** [comment]
Hm it seems like it is not supported any more, but it still works and as a workaround so I fell back to it for now. I did not have the time to verify if it is a bug in PhpStorm or intentionally removed.

**Comment by peterjaap** [comment]
Strange, I couldn't get the Remote call plugin to work when I tried it a while back.

**Comment by DanieliMi** [comment]
That is strange. This is what I currently have applied for it to work:
```
Index: src/components/Editor.vue
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/components/Editor.vue b/src/components/Editor.vue
--- a/src/components/Editor.vue	(revision 8cc6fa64c611be9a4149e6d3043066f3bbdc9b87)
+++ b/src/components/Editor.vue	(date 1670404211501)
@@ -83,8 +83,8 @@
       <div class="w-1/2 px-4 py-2 overflow-y-scroll bg-orange-200">
         <h2 class="mb-4 font-bold">Diff</h2>
         <h3 class="mb-4 font-bold">
-          <a :href="'http://localhost:63342/api/file?file=' + relativePathVendorFileOrig" target="phpstorm-api-call">Original vendor file</a> |
-          <a :href="'http://localhost:63342/api/file?file=' + relativePathVendorFile" target="phpstorm-api-call">New vendor file</a> |
+          <a :href="'http://localhost:8091/?message=' + relativePathVendorFileOrig" target="phpstorm-api-call">Original vendor file</a> |
+          <a :href="'http://localhost:8091/?message=' + relativePathVendorFile" target="phpstorm-api-call">New vendor file</a> |
           <a href="#" @click.prevent.self="openThreeWayDiff()">Open three way diff</a>
         </h3>
         <div>
@@ -98,7 +98,7 @@
       </div>
       <div class="w-1/2 px-4 py-2 overflow-y-scroll bg-orange-300">
         <h2 class="mb-4 font-bold">{{ type }}</h2>
-        <h3 class="mb-4 font-bold"><a :href="'http://localhost:63342/api/file?file=' + relativePath" target="phpstorm-api-call">{{ relativePath }}</a></h3>
+        <h3 class="mb-4 font-bold"><a :href="'http://localhost:8091/?message=' + relativePath" target="phpstorm-api-call">{{ relativePath }}</a></h3>
         <div>
           <prism-editor
             class="my-editor custom-file-content-editor height-300"

```
And I have version 1.8 of remote call installed.

I mean this is just a workaround provided it is just a bug with the file API. I am currently trying the new design beta, I did not verify it is not working with the normal design.

**Comment by DanieliMi** [comment]
This one might be a related youtrack issue: https://youtrack.jetbrains.com/issue/IDEA-65879

**Comment by DanieliMi** [comment]
Well I created a separate issue to see what is going on: https://youtrack.jetbrains.com/issue/WI-70125/Opening-a-file-via-API-api-file-does-not-work-anymore-in-PhpStorm-2022.3

**Comment by DanieliMi** [comment]
Ah okay so they removed this functionality (without any notice) and put it into a separate plugin: https://youtrack.jetbrains.com/issue/IDEA-308020/Opening-a-file-via-API-api-file-does-not-work-anymore-in-PhpStorm-2022.3#focus=Comments-27-6732207.0-0. I will test it and make a PR to add a notice to the readme.

**Comment by peterjaap** [comment]
Thanks for figuring it out, I just tested it and it works again :partying_face:
