### ISSUE TITLE
patch-helper-output.txt file not found

### ISSUE THREAD

**Issue by simthax** [elgentos/magento2-upgrade-gui#14]
After opening my Magento project dir in the GUI, I got the following error : `No patch-helper-output.txt overview file found in your Magento 2 project directory!` although I got all the infos after running the patch helper command.

**Comment by peterjaap** [comment]
Are you using 1.3.5? Which files do you have in your project dir? The GUI looks for `warnings.json`, `infoNotices.json` and `patch-helper-output.txt`. If all of these files don't exist, you'll get the above mentioned warning.

So you either have `patch-helper-output.txt` in your project, or both `warnings.json` and `infoNotices.json`.

**Comment by simthax** [comment]
Yes I'm using 1.3.5> It seems that the patch helper command didn't generate the file `patch-helper-output.txt`

**Comment by simthax** [comment]
Yes, I'm using 1.3.5. It's ok now, I didn't know that this file had to be generated manually.
Thanks

**Comment by omarabdelazizgamal** [comment]
> Yes, I'm using 1.3.5. It's ok now, I didn't know that this file had to be generated manually. Thanks

How this file is generated manually?

**Comment by peterjaap** [comment]
@omarabdelazizgamal @simthax that file isn't generated manually, it's generated by https://github.com/idhlagency/ampersand-magento2-upgrade-patch-helper
