### ISSUE TITLE
Path to overwrite is generated wrong

### ISSUE THREAD

**Issue by DanieliMi** [elgentos/magento2-upgrade-gui#2]
PHP classes (overrides) won't display. I generated the autoload files with  `composer dump`, generated the classmap.json with `php -r "\$classmap=require_once('vendor/composer/autoload_classmap.php'); echo json_encode(\$classmap);" > classmap.json` and then started the electron app and selected the projects directory. The paths in the classmap.json are absolute but the project path is still prepended so the file cannot be found and it results in "Could not find contents of /path/to/file".

Here the entry from classmap.json:
```
"Mirasvit\\Core\\Plugin\\UrlRewritePlugin": "\/home\/dga\/projects\/example.com\/vendor\/mirasvit\/module-core\/src\/Core\/Plugin\/UrlRewritePlugin.php",
```
Result:  
![wrong_path_example](https://user-images.githubusercontent.com/31039652/159959624-b3ec98cb-2988-45aa-a63f-bc269515680d.png)

**Comment by peterjaap** [comment]
You're correct. We have accommodated for the [setup we use](https://github.com/JeroenBoersma/docker-compose-development) but nothing outside of that. 

Our absolute paths are for example `/data/clientname/magento2/vendor/php-parallel-lint/php-parallel-lint/src/Output.php` and we strip off the `/data` part [here](https://github.com/elgentos/magento2-upgrade-gui/blob/07dfb9502555877479c9d5bf0992ba8c31811eac/src/components/OverrideSelector.vue#L218) and [here](https://github.com/elgentos/magento2-upgrade-gui/blob/07dfb9502555877479c9d5bf0992ba8c31811eac/src/components/OverrideSelector.vue#L245). If you're willing to do a PR for a fix that would cover both scenarios, I'd be happy to merge it!

**Comment by DanieliMi** [comment]
@peterjaap I'm happy to do a PR. I am wondering what your intention is with the `copyPasteableFilePath` is. What does `http://localhost:8091?message=' + copyPasteableFilePath` do? For me it simply opens this url in the electron app and has no result but a blank page.  
I am not quite sure why you added the `fixPath` method, since the `classmap.json` contains absolute paths anyway it does not seem to be needed. I am asking because I do not want to break your workflow.

**Comment by DanieliMi** [comment]
Ah I see the fixing is needed for all files that are no PHP classes. Okay I get that part now ;)

**Comment by peterjaap** [comment]
@DanieliMi the copypasteablepath is clickable when you have the PhpStorm plugin [Remote Call](https://plugins.jetbrains.com/plugin/6027-remote-call) installed. It will open that file in your IDE.

**Comment by DanieliMi** [comment]
@peterjaap ah that's pretty cool! Then it should be no problem, actually be good, to use the absolute path here as well. The absolute path cannot be ambiguous.

**Comment by peterjaap** [comment]
@DanieliMi actually we need relative paths there because we run everything in Docker containers so the absolute path in the container does not correspond to the absolute path on my machine.

**Comment by DanieliMi** [comment]
@peterjaap  I see. And for that you need the `data/` part removed.

**Comment by peterjaap** [comment]
Exactly
