### ISSUE TITLE
PHPStorm Integration

### ISSUE THREAD

**Issue by norgeindian** [elgentos/magento2-upgrade-gui#4]
Awesome tool, thanks a lot for developing it.
Do you see any good way of integrating it directly into PHPStorm, so it can be used to also apply the needed changes?
I'm thinking of a three-file-diff viewer, where you can directly see the changes of your override / preference to the current code and the old version.
Do you see any good approach for that?

**Comment by peterjaap** [comment]
Sorry, no idea. That would involve writing a plugin in PhpStorm, which is Java, which I don't know.

But how does that differ from the functionality that this tool gives you? Maybe I can incorporate your idea into this tool?

**Comment by norgeindian** [comment]
@peterjaap , thanks for coming back to me this fast. 
I think it could be easier, than we think. My issue is, that currently, I would need to open the file in PHPStorm to actually apply changes I found in the diff of the GUI.
In the diff viewer, you have the possibility to directly include changes:
![image](https://user-images.githubusercontent.com/11156287/193997264-0c933ca5-2907-41e4-8ef0-6a6fc642f5bd.png)

So if we would have all three files together, we would directly see, which changes are needed and could apply them directly.
How do you currently open the needed file, when clicking on it?
Would it be an idea, to add a new link / button, which then works like described [here](https://www.jetbrains.com/help/phpstorm/command-line-differences-viewer.html#43842d6c)

**Comment by peterjaap** [comment]
@norgeindian I didn't know about that option, I tried it with the "Original vendor file", "New vendor file" and "Override";

```
phpstorm diff vendor_orig/magento/module-bundle/view/base/templates/product/price/tier_prices.phtml vendor/magento/module-bundle/view/base/templates/product/price/tier_prices.phtml app/design/frontend/Xs2event_Hyva/default/Magento_Bundle/templates/product/price/tier_prices.phtml
```

![image](https://user-images.githubusercontent.com/431360/194041468-58a4dbb3-c9bf-4c26-a98e-8eb1d959c056.png)

It doesn't add much functionality as far as I can see? I can click the corner-right arrow in the blue area to merge that change from the 3rd file (Magento 2.4.5 core) into the middle file (override), but I can't merge the other ones.

**Comment by peterjaap** [comment]
@norgeindian allright, that was easy. I added a button "Open three way diff":

![image](https://user-images.githubusercontent.com/431360/194045448-d6d3d17b-3f1a-451c-842a-bff4ceae769e.png)

Clicking it will open a three way diff in PhpStorm;

![image](https://user-images.githubusercontent.com/431360/194045502-6feaed0c-13f9-4a6f-ba14-b696169c0d0c.png)

Here's the commit https://github.com/elgentos/magento2-upgrade-gui/commit/26cfa8040568669a69b4b59625fb41cede9444ce

**Comment by peterjaap** [comment]
Done! Nice small addition, could help in certain circumstances.

**Comment by norgeindian** [comment]
@peterjaap , awesome. That's exactly what I needed. Amazing, thanks.

**Comment by norgeindian** [comment]
@peterjaap , would you mind, publishing a new release for this feature, so I can already use it?

**Comment by peterjaap** [comment]
@norgeindian I wanted to wait before making a release, so you could test it :) You can just clone the repo, hit `yarn install` and `yarn electron:serve`, see https://github.com/elgentos/magento2-upgrade-gui#development

**Comment by peterjaap** [comment]
@norgeindian but I made a built file for you locally; https://wetransfer.com/downloads/6328741f9abc789fa7c2fa34d828445020221005112823/e981910d6a52f9c610b522d97ec3630220221005112833/c1a2b3

**Comment by norgeindian** [comment]
@peterjaap , thanks, that's really amazing and exactly what I was searching for. Works perfectly.
This way you can now shortly check in the GUI, if an update is needed and then do it in PHPStorm directly. Thanks a lot for including that feature.

**Comment by peterjaap** [comment]
@norgeindian awesome, I'll create a new release

**Comment by norgeindian** [comment]
@peterjaap . I'm just doing my first big update with the new feature. It's really awesome and saves me so much time. Thanks a lot for including it.

**Comment by peterjaap** [comment]
@norgeindian awesome to hear! I've also used it a couple of times, it is indeed a time saver!
