### ISSUE TITLE
Auto open last project directory or open project via command line

### ISSUE THREAD

**Issue by amenk** [elgentos/magento2-upgrade-gui#6]
I am a bit lazy to always open the project after reopening the tool.

I tried

` ./magento2-upgrade-gui-1.3.1_aa651f98e6ea2127c1f61208920bea4d.AppImage ~/my/projects/example.com`

but that does not work.

As an alternative it would be nice if the last open project ist loaded automatically.

**Comment by amenk** [comment]
As a workaround I can bookmark the project-dir in my GNOME-file-chooser :-)

**Comment by peterjaap** [comment]
@amenk aah I was just about to build this last weekend and I got side-tracked, but I share your pain! I use the bookmark-workaround in GNOME file chooser as well for now, but this is definitely something I want/need as well ;)

**Comment by peterjaap** [comment]
Added in https://github.com/elgentos/magento2-upgrade-gui/releases/tag/v1.3.2

**Comment by amenk** [comment]
Thanks you so much

**Comment by amenk** [comment]
Works well ... 
but some small issue. When using https://github.com/TheAssassin/AppImageLauncher to integrate the app image, it seems to add the parameter `--no-sandbox` which causes error messages.

**Comment by peterjaap** [comment]
I'm not familiar with that tool. What kind of error messages and how can we fix it?

**Comment by amenk** [comment]
The error message  (amongst other file-not-founds)

![image](https://user-images.githubusercontent.com/1087128/205268644-2a1b7b8d-79f4-448a-b478-5e7a0e69211e.png)

I think just parameters like --no-sandbox should not be threated like a folder name and ignore :-)

**Comment by peterjaap** [comment]
Right, we need a small lib like [yargs](https://www.npmjs.com/package/yargs) to actually parse arguments instead of just grabbing the first string in argv; https://github.com/elgentos/magento2-upgrade-gui/commit/400c465af82d2b9d52eca3743e1fe31580784f4f#diff-16f022ec89282b37542e3374910a5e4a4cf37596abf8f723f0d7f8ab1096f853R34

**Comment by amenk** [comment]
Tested, works well - thanks :-)
