### ISSUE TITLE
How is the resolve tracking supposed to work in detail

### ISSUE THREAD

**Issue by amenk** [elgentos/magento2-upgrade-gui#7]
> If you have this feature enabled (default), it will add the file to the git stage and commit to your repository when you click "Resolve".

https://github.com/elgentos/magento2-upgrade-gui#git-auto-commit 

Is this about the file edited ? So the right side?

It does not seem to work.

For me it would be enough if the warings.json is updated and the states are kept until the next time I open the tool - but it seems not to be updated.
Not sure if this is a bug, a feature or we just should improve the docs :-)

We don't work with the GitLab integration (which sounds pretty awesome), because we don't use GitLab for issue tracking (but redmine).

**Comment by amenk** [comment]
The `results.md` / `results.json` are updated though, but not the `warnings.json`.

**Comment by peterjaap** [comment]
If you edit your override (so the file on the right) in your IDE, and then click Resolve, it'll auto-commit it to the repo. It's pretty "dumb" in the sense that it just runs a `git add` followed by a `git commit` on the command line; https://github.com/elgentos/magento2-upgrade-gui/blob/8302ac99d9b731b16a1054a98bb728c9e5c9beac/src/background.js#L67

**Comment by peterjaap** [comment]
@amenk for the results.json/warnings.json, I've create a new issue, that is indeed an oversight on my part https://github.com/elgentos/magento2-upgrade-gui/issues/8

**Comment by amenk** [comment]
With the fix it is pretty much clear now - can as well be closed.
