### ISSUE TITLE
results.json is still updated, instead of separated warnings.json and infoNotices.json

### ISSUE THREAD

**Issue by peterjaap** [elgentos/magento2-upgrade-gui#8]
See https://github.com/elgentos/magento2-upgrade-gui/blob/8302ac99d9b731b16a1054a98bb728c9e5c9beac/src/components/Editor.vue#L317

**Comment by peterjaap** [comment]
Fixed in https://github.com/elgentos/magento2-upgrade-gui/releases/tag/v1.3.2

**Comment by amenk** [comment]
Works well. Restarting the app now preserves the state. Thank you
